name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Docker/Controller/Dockerfile
            image: docker.io/slamswarm:controller
          - dockerfile: ./Docker/PI/Dockerfile
            image: docker.io/slamswarm:pi
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image Drill4Net.Agent.Service
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      # - name: Build image and push to Docker Hub and GitHub Container Registry
      #   uses: docker/build-push-action@v2
      #   with:
      #     # relative path to the place where source code with Dockerfile is located
      #     context: ./Jetson/AprilTag
      #     # Note: tags has to be all lower-case
      #     tags: |
      #       assubram/apriltag:latest
      #     # build on feature branches, push only on main branch
      #     push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
